package vista;

import javax.swing.table.DefaultTableModel;
import controlador.CControlAdministracion;
import java.util.ArrayList;
import modelo.CClientes;

public class Administracion extends javax.swing.JFrame {

    DefaultTableModel modelo;
    CControlAdministracion c = new CControlAdministracion();

    public Administracion() {
        initComponents();

        modelo = (DefaultTableModel) tabla.getModel();
        tabla.setShowHorizontalLines(true);
        tabla.setShowVerticalLines(true);
        tabla.setGridColor(java.awt.Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Ciudad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NumeroCuenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Saldo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        CerrarCliente = new javax.swing.JButton();
        AdministracionCajeros = new javax.swing.JButton();
        ListarCliente = new javax.swing.JButton();
        AgregarCliente = new javax.swing.JButton();
        EditarCliente = new javax.swing.JButton();
        EliminarCliente = new javax.swing.JButton();
        BuscarNombreCliente = new javax.swing.JButton();
        BuscarIDCliente = new javax.swing.JButton();
        ConsignarDineroCliente = new javax.swing.JButton();
        RetirarDineroCliente = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        IDCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DineroConsignar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DineroRetirar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADMINISTRACION");

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Teléfono:");

        jLabel5.setText("Ciudad:");

        jLabel6.setText("Número Cuenta:");

        jLabel7.setText("Saldo:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Teléfono", "Ciudad", "Número Cuenta", "Saldo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        CerrarCliente.setText("Cerrar");
        CerrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarClienteActionPerformed(evt);
            }
        });

        AdministracionCajeros.setText("Adiministración Cajeros");
        AdministracionCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministracionCajerosActionPerformed(evt);
            }
        });

        ListarCliente.setText("Listar");
        ListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarClienteActionPerformed(evt);
            }
        });

        AgregarCliente.setText("Agregar");
        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });

        EditarCliente.setText("Editar");
        EditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarClienteActionPerformed(evt);
            }
        });

        EliminarCliente.setText("Eliminar");
        EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteActionPerformed(evt);
            }
        });

        BuscarNombreCliente.setText("Buscar por nombre");
        BuscarNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNombreClienteActionPerformed(evt);
            }
        });

        BuscarIDCliente.setText("Buscar por ID");
        BuscarIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIDClienteActionPerformed(evt);
            }
        });

        ConsignarDineroCliente.setText("Consignar");
        ConsignarDineroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsignarDineroClienteActionPerformed(evt);
            }
        });

        RetirarDineroCliente.setText("Retirar");
        RetirarDineroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarDineroClienteActionPerformed(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane2.setViewportView(salida);

        jLabel8.setText("ID cliente:");

        jLabel9.setText("Dinero para consignar:");

        jLabel10.setText("Dinero para retirar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Apellido)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ciudad)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(IDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(DineroConsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(DineroRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(327, 327, 327))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Volver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AdministracionCajeros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CerrarCliente)
                                .addContainerGap())))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ListarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgregarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EliminarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConsignarDineroCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RetirarDineroCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BuscarNombreCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarIDCliente))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(NumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(IDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(DineroConsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(DineroRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarCliente)
                    .addComponent(AgregarCliente)
                    .addComponent(EditarCliente)
                    .addComponent(EliminarCliente)
                    .addComponent(BuscarNombreCliente)
                    .addComponent(BuscarIDCliente)
                    .addComponent(ConsignarDineroCliente)
                    .addComponent(RetirarDineroCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CerrarCliente)
                    .addComponent(AdministracionCajeros)
                    .addComponent(Volver))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarClienteActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_CerrarClienteActionPerformed

    private void AdministracionCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministracionCajerosActionPerformed
        // TODO add your handling code here:

        AdministracionCajero p = new AdministracionCajero();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_AdministracionCajerosActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:

        Principal p = new Principal();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void ListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarClienteActionPerformed
        // TODO add your handling code here:

        ArrayList<CClientes> lista = new ArrayList<>();
        lista = c.ListarClientes();

        modelo.setRowCount(0);
        boolean hayDatos = false;
        for (CClientes con : lista) {
            modelo.addRow(new Object[]{con.getId(), con.getNombre(), con.getApellido(), con.getTelefono(), con.getCiudad(), con.getNcuenta(), con.getSaldo(), con.getEstado()});
            hayDatos = true;
        }
        if (hayDatos) {
            salida.setText("Clientes listados correctamente.");
        } else {
            salida.setText("No hay clientes para listar.");
        }
    }//GEN-LAST:event_ListarClienteActionPerformed

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        // TODO add your handling code here:

        if (!Nombre.getText().isEmpty() || !Apellido.getText().isEmpty() || !Telefono.getText().isEmpty() || !Ciudad.getText().isEmpty() || !NumeroCuenta.getText().isEmpty() || !Saldo.getText().isEmpty()) {

            int ncuenta = Integer.parseInt(NumeroCuenta.getText().trim());
            double saldo = Integer.parseInt(Saldo.getText().trim());

            int x = c.IngresarCliente(Nombre.getText(), Apellido.getText(), Telefono.getText(), Ciudad.getText(), ncuenta, saldo);

            if (x == 10) {
                salida.setText("Cliente ingresado.");
            } else if (x == 1) {
                salida.setText("Este cliente ya existe.");
            } else if (x == 0) {
                salida.setText("Error en el sql.");
            }
        } else {
            salida.setText("Ingrese los datos para agregar el cliente.");
        }
    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void EditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarClienteActionPerformed
        // TODO add your handling code here:

        if (!Nombre.getText().isEmpty() || !Apellido.getText().isEmpty() || !Telefono.getText().isEmpty() || !Ciudad.getText().isEmpty() || !NumeroCuenta.getText().isEmpty() || !Saldo.getText().isEmpty() || !IDCliente.getText().isEmpty()) {

            int ncuenta = Integer.parseInt(NumeroCuenta.getText().trim());
            double saldo = Integer.parseInt(Saldo.getText().trim());
            int idcliente = Integer.parseInt(IDCliente.getText().trim());

            int x = c.EditarCliente(idcliente, Nombre.getText(), Apellido.getText(), Telefono.getText(), Ciudad.getText(), ncuenta, saldo);

            if (x == 10) {
                salida.setText("Se editó el cliente correctamente.");
            } else if (x == 1) {
                salida.setText("El cliente se encuentra ocupado.");
            } else if (x == 11) {
                salida.setText("No existe un cliente con el id " + idcliente + ".");
            } else if (x == 0) {
                salida.setText("Error en el sql.");
            }
        } else {
            salida.setText("Ingrese los datos para editar el cliente.");
        }
    }//GEN-LAST:event_EditarClienteActionPerformed

    private void EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClienteActionPerformed
        // TODO add your handling code here:

        if (!IDCliente.getText().isEmpty()) {

            int idcliente = Integer.parseInt(IDCliente.getText().trim());

            int x = c.EliminarCliente(idcliente);

            if (x == 10) {
                salida.setText("Se eliminó el cliente correctamente.");
            } else if (x == 1) {
                salida.setText("El cliente se encuentra ocupado.");
            } else if (x == 11) {
                salida.setText("No existe un cliente con el id " + idcliente + ".");
            } else if (x == 0) {
                salida.setText("Error en el sql.");
            }
        } else {
            salida.setText("Ingrese el id para eliminar el cliente.");
        }
    }//GEN-LAST:event_EliminarClienteActionPerformed

    private void BuscarNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNombreClienteActionPerformed
        // TODO add your handling code here:

        if (!Nombre.getText().isEmpty()) {

            ArrayList<CClientes> lista = new ArrayList<>();
            modelo.setRowCount(0);

            lista = c.BuscarPorNombre(Nombre.getText());

            boolean hayDatos = false;
            for (CClientes con : lista) {
                modelo.addRow(new Object[]{con.getId(), con.getNombre(), con.getApellido(), con.getTelefono(), con.getCiudad(), con.getNcuenta(), con.getSaldo(), con.getEstado()});
                hayDatos = true;
            }
            if (hayDatos) {
                salida.setText("Clientes con el nombre " + Nombre.getText() + " listados.");
            } else {
                salida.setText("No hay clientes con ese nombre.");
            }
        } else {
            salida.setText("Ingrese un nombre para buscar.");
        }
    }//GEN-LAST:event_BuscarNombreClienteActionPerformed

    private void BuscarIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIDClienteActionPerformed
        // TODO add your handling code here:

        if (!IDCliente.getText().isEmpty()) {

            ArrayList<CClientes> lista = new ArrayList<>();
            int idcliente = Integer.parseInt(IDCliente.getText().trim());
            modelo.setRowCount(0);

            lista = c.BuscarPorId(idcliente);

            boolean hayDatos = false;
            for (CClientes con : lista) {
                modelo.addRow(new Object[]{con.getId(), con.getNombre(), con.getApellido(), con.getTelefono(), con.getCiudad(), con.getNcuenta(), con.getSaldo(), con.getEstado()});
                hayDatos = true;
            }
            if (hayDatos) {
                salida.setText("Cliente con el id " + idcliente + " consultado.");
            } else {
                salida.setText("No existe un cliente con ese id.");
            }
        } else {
            salida.setText("Ingrese un id para buscar.");
        }
    }//GEN-LAST:event_BuscarIDClienteActionPerformed

    private void ConsignarDineroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsignarDineroClienteActionPerformed
        // TODO add your handling code here:

        if (!IDCliente.getText().isEmpty() || !DineroConsignar.getText().isEmpty()) {

            int idcliente = Integer.parseInt(IDCliente.getText().trim());
            double dinero = Integer.parseInt(DineroConsignar.getText().trim());

            int x = c.ConsignarDineroCliente(idcliente, dinero);

            if (x == 10) {
                salida.setText("Consignación realizada.");
            } else if (x == 1) {
                salida.setText("El cliente se encuentra ocupado.");
            } else if (x == 11) {
                salida.setText("No existe un cliente con el id " + idcliente + ".");
            } else if (x == 0) {
                salida.setText("Error en el sql.");
            }
        } else {
            salida.setText("Ingrese el id del cliente y cuanto dinero va a consignar.");
        }
    }//GEN-LAST:event_ConsignarDineroClienteActionPerformed

    private void RetirarDineroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarDineroClienteActionPerformed
        // TODO add your handling code here:

        if (!IDCliente.getText().isEmpty() || !DineroRetirar.getText().isEmpty()) {

            int idcliente = Integer.parseInt(IDCliente.getText().trim());
            double dinero = Integer.parseInt(DineroRetirar.getText().trim());

            int x = c.RetirarDineroCliente(idcliente, dinero);
            
            if (x == 10) {
                salida.setText("Retiro realizado.");
            } else if (x == 1) {
                salida.setText("El cliente se encuentra ocupado.");
            } else if (x == 101) {
                salida.setText("El dinero no es suficiente para retirar la cantidad de: " + dinero + ".");
            } else if (x == 11) {
                salida.setText("No existe un cliente con el id " + idcliente + ".");
            } else if (x == 0) {
                salida.setText("Error en el sql.");
            }
        } else {
            salida.setText("Ingrese el id del cliente y cuanto dinero va a retirar.");
        }
    }//GEN-LAST:event_RetirarDineroClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdministracionCajeros;
    private javax.swing.JButton AgregarCliente;
    private javax.swing.JTextField Apellido;
    private javax.swing.JButton BuscarIDCliente;
    private javax.swing.JButton BuscarNombreCliente;
    private javax.swing.JButton CerrarCliente;
    private javax.swing.JTextField Ciudad;
    private javax.swing.JButton ConsignarDineroCliente;
    private javax.swing.JTextField DineroConsignar;
    private javax.swing.JTextField DineroRetirar;
    private javax.swing.JButton EditarCliente;
    private javax.swing.JButton EliminarCliente;
    private javax.swing.JTextField IDCliente;
    private javax.swing.JButton ListarCliente;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField NumeroCuenta;
    private javax.swing.JButton RetirarDineroCliente;
    private javax.swing.JTextField Saldo;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea salida;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
