package vista;

import javax.swing.table.DefaultTableModel;
import controlador.CControlAdministracion;
import java.util.ArrayList;
import modelo.CCajeros;

public class AdministracionCajero extends javax.swing.JFrame {

    DefaultTableModel modelo;
    CControlAdministracion c = new CControlAdministracion();

    public AdministracionCajero() {
        initComponents();

        modelo = (DefaultTableModel) tabla.getModel();
        tabla.setShowHorizontalLines(true);
        tabla.setShowVerticalLines(true);
        tabla.setGridColor(java.awt.Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BilletesVeinte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BilletesCincuenta = new javax.swing.JTextField();
        BilletesCien = new javax.swing.JTextField();
        CerrarCajero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        ListarCajero = new javax.swing.JButton();
        AgregarCajero = new javax.swing.JButton();
        EditarCajero = new javax.swing.JButton();
        EliminarCajero = new javax.swing.JButton();
        AgregarBilletesCajero = new javax.swing.JButton();
        QuitarBilletesCajero = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        Volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        IDCajero = new javax.swing.JTextField();
        BilletesDiez = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADMINISTRACIÓN CAJEROS");

        jLabel2.setText("Billetes de Diez:");

        jLabel3.setText("Billetes de Veinte:");

        jLabel4.setText("Billetes de Cincuenta:");

        jLabel5.setText("Billetes de Cien:");

        CerrarCajero.setText("Cerrar");
        CerrarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarCajeroActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Billetes de diez", "Billetes de veinte", "Billetes de cincuenta", "Billetes de cien", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        ListarCajero.setText("Listar");
        ListarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCajeroActionPerformed(evt);
            }
        });

        AgregarCajero.setText("Agregar");
        AgregarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCajeroActionPerformed(evt);
            }
        });

        EditarCajero.setText("Editar");
        EditarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarCajeroActionPerformed(evt);
            }
        });

        EliminarCajero.setText("Eliminar");
        EliminarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCajeroActionPerformed(evt);
            }
        });

        AgregarBilletesCajero.setText("Agregar billetes");
        AgregarBilletesCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBilletesCajeroActionPerformed(evt);
            }
        });

        QuitarBilletesCajero.setText("Quitar billetes");
        QuitarBilletesCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarBilletesCajeroActionPerformed(evt);
            }
        });

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane2.setViewportView(salida);

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        jLabel6.setText("ID cajero:");

        BilletesDiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BilletesDiezActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BilletesVeinte, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BilletesDiez)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(233, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BilletesCien, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BilletesCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(166, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CerrarCajero))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ListarCajero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AgregarCajero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EditarCajero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EliminarCajero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AgregarBilletesCajero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(QuitarBilletesCajero))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(BilletesCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BilletesDiez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IDCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BilletesVeinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BilletesCien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarCajero)
                    .addComponent(AgregarCajero)
                    .addComponent(EditarCajero)
                    .addComponent(EliminarCajero)
                    .addComponent(AgregarBilletesCajero)
                    .addComponent(QuitarBilletesCajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CerrarCajero)
                    .addComponent(Volver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCajeroActionPerformed
        // TODO add your handling code here:

        ArrayList<CCajeros> lista = new ArrayList<>();
        lista = c.ListarCajeros();

        modelo.setRowCount(0);
        boolean hayDatos = false;
        for (CCajeros con : lista) {
            modelo.addRow(new Object[]{con.getId(), con.getNdiez(), con.getNveinte(), con.getNcincuenta(), con.getNcien(), con.getEstado()});
            hayDatos = true;
        }
        if (hayDatos) {
            salida.setText("Cajeros listados correctamente.");
        } else {
            salida.setText("No hay cajeros para listar.");
        }
    }//GEN-LAST:event_ListarCajeroActionPerformed

    private void CerrarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarCajeroActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_CerrarCajeroActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:

        Administracion p = new Administracion();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void AgregarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCajeroActionPerformed
        // TODO add your handling code here:

        if (!BilletesDiez.getText().isEmpty() && !BilletesVeinte.getText().isEmpty() && !BilletesCincuenta.getText().isEmpty() && !BilletesCien.getText().isEmpty()) {

            int ndiez = Integer.parseInt(BilletesDiez.getText().trim());
            int nveinte = Integer.parseInt(BilletesVeinte.getText().trim());
            int ncincuenta = Integer.parseInt(BilletesCincuenta.getText().trim());
            int ncien = Integer.parseInt(BilletesCien.getText().trim());

            int x = c.IngresarCajero(ndiez, nveinte, ncincuenta, ncien);

            if (x == 10) {
                salida.setText("Se agregó el cajero correctamente.");
            } else if (x == 0) {
                salida.setText("No se pudo agregar el cajero.");
            }
        } else {
            salida.setText("Ingrese los datos para agregar el cajero.");
        }
    }//GEN-LAST:event_AgregarCajeroActionPerformed

    private void EditarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarCajeroActionPerformed
        // TODO add your handling code here:

        if (!BilletesDiez.getText().isEmpty() && !BilletesVeinte.getText().isEmpty() && !BilletesCincuenta.getText().isEmpty() && !BilletesCien.getText().isEmpty() && !IDCajero.getText().isEmpty()) {

            int ndiez = Integer.parseInt(BilletesDiez.getText().trim());
            int nveinte = Integer.parseInt(BilletesVeinte.getText().trim());
            int ncincuenta = Integer.parseInt(BilletesCincuenta.getText().trim());
            int ncien = Integer.parseInt(BilletesCien.getText().trim());
            int idcajero = Integer.parseInt(IDCajero.getText().trim());

            int x = c.EditarCajero(idcajero, ndiez, nveinte, ncincuenta, ncien);

            if (x == 10) {
                salida.setText("Se editó el cajero correctamente.");
            } else if (x == 1) {
                salida.setText("El cajero se encuentra ocupado.");
            } else if (x == 11) {
                salida.setText("No existe un cajero con el id " + idcajero + ".");
            } else if (x == 0) {
                salida.setText("Error en el sql.");
            }
        } else {
            salida.setText("Ingrese los datos para editar el cajero.");
        }
    }//GEN-LAST:event_EditarCajeroActionPerformed

    private void BilletesDiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BilletesDiezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BilletesDiezActionPerformed

    private void EliminarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCajeroActionPerformed
        // TODO add your handling code here:

        if (!IDCajero.getText().isEmpty()) {

            int idcajero = Integer.parseInt(IDCajero.getText().trim());

            int x = c.EliminarCajero(idcajero);

            if (x == 10) {
                salida.setText("Se eliminó el cajero correctamente.");
            } else if (x == 1) {
                salida.setText("El cajero se encuentra ocupado.");
            } else if (x == 11) {
                salida.setText("No existe un cajero con el id " + idcajero + ".");
            } else if (x == 0) {
                salida.setText("Error en el sql.");
            }
        } else {
            salida.setText("Ingrese el id para eliminar el cajero.");
        }
    }//GEN-LAST:event_EliminarCajeroActionPerformed

    private void AgregarBilletesCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBilletesCajeroActionPerformed
        // TODO add your handling code here:

        if (!BilletesDiez.getText().isEmpty() && !BilletesVeinte.getText().isEmpty() && !BilletesCincuenta.getText().isEmpty() && !BilletesCien.getText().isEmpty() && !IDCajero.getText().isEmpty()) {

            int idcajero = Integer.parseInt(IDCajero.getText().trim());
            int ndiez = Integer.parseInt(BilletesDiez.getText().trim());
            int nveinte = Integer.parseInt(BilletesVeinte.getText().trim());
            int ncincuenta = Integer.parseInt(BilletesCincuenta.getText().trim());
            int ncien = Integer.parseInt(BilletesCien.getText().trim());

            int x = c.AgregarBilletesCajero(idcajero, ndiez, nveinte, ncincuenta, ncien);

            if (x == 10) {
                salida.setText("Agregación realizada.");
            } else if (x == 1) {
                salida.setText("El cajero se encuentra ocupado.");
            } else if (x == 11) {
                salida.setText("No existe un cajero con el id " + idcajero + ".");
            } else if (x == 0) {
                salida.setText("Error en el sql.");
            }
        } else {
            salida.setText("Ingrese la cantidad de billetes que quiere ingresar al cajero.");
        }
    }//GEN-LAST:event_AgregarBilletesCajeroActionPerformed

    private void QuitarBilletesCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarBilletesCajeroActionPerformed
        // TODO add your handling code here:

        if (!BilletesDiez.getText().isEmpty() && !BilletesVeinte.getText().isEmpty() && !BilletesCincuenta.getText().isEmpty() && !BilletesCien.getText().isEmpty() && !IDCajero.getText().isEmpty()) {

            int idcajero = Integer.parseInt(IDCajero.getText().trim());
            int ndiez = Integer.parseInt(BilletesDiez.getText().trim());
            int nveinte = Integer.parseInt(BilletesVeinte.getText().trim());
            int ncincuenta = Integer.parseInt(BilletesCincuenta.getText().trim());
            int ncien = Integer.parseInt(BilletesCien.getText().trim());

            int x = c.QuitarBilletesCajero(idcajero, ndiez, nveinte, ncincuenta, ncien);
            
            if (x == 10) {
                salida.setText("Descuento de billetes realizado.");
            } else if (x == 1) {
                salida.setText("El cajero se encuentra ocupado.");
            } else if (x == 101) {
                salida.setText("El cajero no cuenta con los billetes suficientes para retirar la cantidad recibida.");
            } else if (x == 11) {
                salida.setText("No existe un cajero con el id " + idcajero + ".");
            } else if (x == 0) {
                salida.setText("Error en el sql.");
            }
        } else {
            salida.setText("Ingrese la cantidad de billetes que quiere retirar del cajero.");
        }
    }//GEN-LAST:event_QuitarBilletesCajeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBilletesCajero;
    private javax.swing.JButton AgregarCajero;
    private javax.swing.JTextField BilletesCien;
    private javax.swing.JTextField BilletesCincuenta;
    private javax.swing.JTextField BilletesDiez;
    private javax.swing.JTextField BilletesVeinte;
    private javax.swing.JButton CerrarCajero;
    private javax.swing.JButton EditarCajero;
    private javax.swing.JButton EliminarCajero;
    private javax.swing.JTextField IDCajero;
    private javax.swing.JButton ListarCajero;
    private javax.swing.JButton QuitarBilletesCajero;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea salida;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
